### PR TITLE
Paul/aes tz

### PR DESCRIPTION
**Pull request by b0b0blaaah**
First TZ/QSEECOM driver implementation to seal/unseal data on locked boxes.

@wellsie @mrakes @erikarn @jimbotse @dressupgeekout @MikolajZuberek

### CODE REVIEW

**Comment by dressupgeekout** [comment]
😮

**Comment by dressupgeekout** [comment]
Does it make sense to also include a Hulafile?

**Comment by b0b0blaaah** [comment]
I don't think so, this is in bw-oss.

**Comment by dressupgeekout** [comment]
Would it eventually make sense to include a Hulafile?

**Comment by b0b0blaaah** [comment]
Yes, totally.  Until it's private, I'm adding it to the hula pkgs collection.

**Pull request merged**
